// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/11/5 17:52:14
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["E:/code/blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/code/blog/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/code/blog/components/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/code/blog/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/code/blog/plugins/**/*.{js,ts,mjs}","E:/code/blog/composables/**/*.{js,ts,mjs}","E:/code/blog/utils/**/*.{js,ts,mjs}","E:/code/blog/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","E:/code/blog/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","E:/code/blog/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","E:/code/blog/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["17"] = "E:/code/blog/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;